name: lotus
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # ignore: sort_pub_dependencies
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4

  sidebarx:
    git:
      url: https://github.com/mrhaubrich/sidebarx.git
  auto_size_text: ^3.0.0

  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1
  file_picker: ^8.1.2
  super_context_menu: ^0.8.22
  adaptive_theme: ^3.6.0
  window_manager: ^0.4.2
  super_sliver_list: ^0.4.1
  hotkey_manager: ^0.2.3
  keymap: ^0.0.92
  flutter_svg: ^2.0.10
  vector_graphics: ^1.1.11
  hugeicons: ^0.0.7
  timeago: ^3.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_layout_grid: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ignore: sort_pub_dependencies
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_to_debian: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/lotus_icon.png
    - assets/logo/ucs-logo.svg.vec
    - assets/ativos/